import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
process.env.NODE_ENV='test';process.env.DATA_DIR=mkdtempSync(join(tmpdir(),'cc-favorites-'));
const {server}=await import('../server/index.js');let base;
before(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`;});
after(async()=>{await new Promise(r=>server.close(r));rmSync(process.env.DATA_DIR,{recursive:true,force:true});});
async function client(){const r=await fetch(base+'/api/store');const state=await r.json(),cookie=r.headers.get('set-cookie').split(';')[0];return {state,async request(path,method='GET',body,csrf=state.csrf){const r=await fetch(base+'/api/'+path,{method,headers:{cookie,'content-type':'application/json','x-csrf-token':csrf},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};}};}
const profile=email=>({email,password:'Favorites2026!',name:'Test Customer',phone:'6142144115',address:'123 Main St',city:'Columbus',state:'OH',zip:'43215'});
test('discounted product price persists and is used by the cart for both sale types',async()=>{
 const c=await client();await c.request('admin/login','POST',{username:'admin',password:'Cricket@2026'});
 const p=c.state.products[1];
 let edit={id:p.id,stock:10,price:10000,regularPrice:10000,previousStock:p.stock,previousPrice:p.price,note:'Discount test',onSale:true,discountType:'percent',discountValue:20};
 assert.equal((await c.request('admin/inventory','PATCH',edit)).status,200);
 let fresh=(await c.request('store')).data.products.find(x=>x.id===p.id);
 assert.equal(fresh.price,8000);assert.equal(fresh.compareAtPrice,10000);assert.equal(fresh.discountValue,20);
 let cart=await c.request('cart','POST',{id:p.id,option:p.options[0],quantity:1});assert.equal(cart.data.subtotal,8000);
 edit={...edit,previousStock:10,previousPrice:8000,discountType:'fixed',discountValue:1500};
 assert.equal((await c.request('admin/inventory','PATCH',edit)).status,200);
 assert.equal((await c.request('store')).data.cart.subtotal,8500);
 const disk=JSON.parse(readFileSync(join(process.env.DATA_DIR,'store.json'),'utf8'));assert.equal(disk.inventory[p.id].price,8500);
 assert.equal((await c.request('admin/inventory','PATCH',{...edit,previousPrice:8500,onSale:false})).status,200);
 fresh=(await c.request('store')).data.products.find(x=>x.id===p.id);assert.equal(fresh.price,10000);assert.equal(fresh.compareAtPrice,0);
});
test('admin sale flag persists alongside New and can be switched off independently',async()=>{
 const c=await client();await c.request('admin/login','POST',{username:'admin',password:'Cricket@2026'});
 const p=c.state.products[0];
 const edit={id:p.id,stock:p.stock,price:p.price,previousStock:p.stock,previousPrice:p.price,note:'Sale badge test',isNew:true,onSale:true,compareAtPrice:p.price+1000};
 assert.equal((await c.request('admin/inventory','PATCH',{...edit,onSale:'yes'})).status,400);
 assert.equal((await c.request('admin/inventory','PATCH',edit)).status,200);
 let fresh=(await c.request('store')).data.products.find(x=>x.id===p.id);
 assert.equal(fresh.onSale,true);assert.equal(fresh.isNew,true);assert.equal(fresh.compareAtPrice,p.price+1000);
 const disk=JSON.parse(readFileSync(join(process.env.DATA_DIR,'store.json'),'utf8'));
 assert.equal(disk.inventory[p.id].onSale,true);
 assert.equal((await c.request('admin/inventory','PATCH',{...edit,onSale:false})).status,200);
 fresh=(await c.request('store')).data.products.find(x=>x.id===p.id);
 assert.equal(fresh.onSale,false);assert.equal(fresh.isNew,true);
});
test('favorites require login, persist per customer, reject CSRF, and remove idempotently',async()=>{
 const a=await client(),b=await client(),id=a.state.products[0].id;
 assert.equal((await a.request('account/saved-items')).status,401);
 assert.equal((await a.request('account/saved-items','PUT',{productId:id})).status,401);
 assert.equal((await a.request('account/register','POST',profile('a@example.com'))).status,200);
 assert.equal((await b.request('account/register','POST',profile('b@example.com'))).status,200);
 assert.equal((await a.request('account/saved-items','PUT',{productId:id},'wrong')).status,403);
 assert.equal((await a.request('account/saved-items','PUT',{productId:'missing'})).status,404);
 assert.deepEqual((await a.request('account/saved-items','PUT',{productId:id})).data.savedItems,[id]);
 assert.deepEqual((await a.request('account/saved-items','PUT',{productId:id})).data.savedItems,[id]);
 assert.deepEqual((await b.request('account/saved-items')).data.savedItems,[]);
 assert.deepEqual((await a.request('store')).data.user.savedItems,[id]);
 const disk=JSON.parse(readFileSync(join(process.env.DATA_DIR,'store.json'),'utf8'));
 assert.deepEqual(disk.users.find(u=>u.email==='a@example.com').savedItems,[id]);
 await a.request('account/logout','POST',{});
 assert.equal((await a.request('account/saved-items')).status,401);
 assert.equal((await a.request('store')).data.user,null);
 const fresh=await client();const login=await fresh.request('account/login','POST',profile('a@example.com'));
 assert.deepEqual(login.data.user.savedItems,[id]);
 assert.deepEqual((await fresh.request('account/saved-items','DELETE',{productId:id})).data.savedItems,[]);
 assert.deepEqual((await fresh.request('account/saved-items','DELETE',{productId:id})).data.savedItems,[]);
});
