<?php namespace App\Http\Controllers; use App\Models\{Product,Category,Order}; use Illuminate\Http\Request;
class StoreController extends Controller {
 public function home(){return view('store.home',['featured'=>Product::active()->where('is_featured',1)->take(8)->get(),'categories'=>Category::where('is_active',1)->orderBy('sort_order')->get()]);}
 public function collection(Request $r,string $slug='all'){ $q=Product::active()->with('category'); $category=null; if($slug!=='all'){ $category=Category::where('slug',$slug)->firstOrFail(); $q->where('category_id',$category->id);} if($r->filled('brand'))$q->whereIn('brand',(array)$r->brand); if($r->filled('min'))$q->where('price','>=',$r->min); if($r->filled('max'))$q->where('price','<=',$r->max); $sort=$r->get('sort','featured'); if($sort==='price-asc')$q->orderBy('price'); elseif($sort==='price-desc')$q->orderByDesc('price'); else $q->orderByDesc('is_featured')->latest(); return view('store.collection',['products'=>$q->paginate(12)->withQueryString(),'category'=>$category,'categories'=>Category::where('is_active',1)->get(),'brands'=>Product::active()->select('brand')->distinct()->orderBy('brand')->pluck('brand')]); }
 public function product(string $slug){$product=Product::active()->where('slug',$slug)->firstOrFail(); return view('store.product',['product'=>$product,'related'=>Product::active()->where('category_id',$product->category_id)->whereKeyNot($product->id)->take(4)->get()]);}
 public function search(Request $r){$term=trim($r->get('q','')); $products=Product::active()->when($term,fn($q)=>$q->where(fn($x)=>$x->where('name','like',"%$term%")->orWhere('brand','like',"%$term%")->orWhere('sku','like',"%$term%")))->paginate(20); return view('store.search',compact('term','products'));}
 public function cart(){return view('store.cart',['cart'=>session('cart',[])]);}
 public function addCart(Request $r,string $slug){$p=Product::active()->where('slug',$slug)->firstOrFail(); $qty=max(1,min((int)$r->get('quantity',1),$p->stock)); abort_if($p->stock<1,422,'Out of stock'); $cart=session('cart',[]); $cart[$p->id]=['id'=>$p->id,'slug'=>$p->slug,'name'=>$p->name,'sku'=>$p->sku,'price'=>(float)$p->price,'quantity'=>min(($cart[$p->id]['quantity']??0)+$qty,$p->stock),'image'=>$p->image]; session(['cart'=>$cart]); return redirect()->route('cart')->with('success','Added to cart');}
 public function updateCart(Request $r){$cart=session('cart',[]); foreach($r->input('qty',[]) as $id=>$qty){$qty=(int)$qty;if($qty<=0)unset($cart[$id]);else $cart[$id]['quantity']=min($qty,Product::findOrFail($id)->stock);} session(['cart'=>$cart]);return back();}
 public function checkout(){abort_if(empty(session('cart',[])),redirect()->route('cart'));return view('store.checkout',['cart'=>session('cart',[])]);}
 public function placeOrder(Request $r){$data=$r->validate(['email'=>'required|email','first_name'=>'required|max:100','last_name'=>'required|max:100','phone'=>'nullable|max:30','address1'=>'required|max:190','address2'=>'nullable|max:190','city'=>'required|max:100','state'=>'required|max:100','postal_code'=>'required|max:20','country'=>'required|max:2']); $cart=session('cart',[]); abort_if(empty($cart),422,'Cart is empty'); $subtotal=collect($cart)->sum(fn($i)=>$i['price']*$i['quantity']); $shipping=$subtotal>=99?0:9.99; $tax=0; $order=\DB::transaction(function()use($data,$cart,$subtotal,$shipping,$tax){foreach($cart as $i){$p=Product::lockForUpdate()->findOrFail($i['id']);abort_if($p->stock<$i['quantity'],422,'Insufficient stock for '.$p->name);$p->decrement('stock',$i['quantity']);} $o=Order::create($data+['order_number'=>'CC'.now()->format('ymd').strtoupper(substr(bin2hex(random_bytes(4)),0,6)),'subtotal'=>$subtotal,'shipping'=>$shipping,'tax'=>$tax,'total'=>$subtotal+$shipping+$tax,'status'=>'pending','payment_status'=>'unpaid']); foreach($cart as $i)$o->items()->create(['product_id'=>$i['id'],'name'=>$i['name'],'sku'=>$i['sku'],'price'=>$i['price'],'quantity'=>$i['quantity'],'image'=>$i['image']]); return $o;}); session()->forget('cart'); return redirect()->route('order.confirmation',$order->order_number);}
 public function confirmation(string $number){$order=Order::with('items')->where('order_number',$number)->firstOrFail();return view('store.confirmation',compact('order'));}
 public function track(Request $r){$order=null;if($r->filled(['order_number','email']))$order=Order::with('items')->where('order_number',$r->order_number)->where('email',$r->email)->first();return view('store.track',compact('order'));}
}